
PRODUCTS = {
    'обувь мужская ботинки': 'obuv/muzhskaya/botinki-i-polubotinki',
    'обувь кеды и кроссовки': 'obuv/muzhskaya/kedy-i-krossovki',
    'обувь мокасины и топсайдеры': 'obuv/muzhskaya/mokasiny-i-topsaydery',
    'обувь лоферы': 'obuv/muzhskaya/tufli-lofery',
    'обувь шлепанцы': 'obuv/muzhskaya/shlepantsy-i-akvasoki',
    'одежда кардиганы': 'muzhchinam/odezhda/dzhempery-i-kardigany',
    'одежда брюки и шорты': 'muzhchinam/odezhda/bryuki-i-shorty',
    'одежда костюмы': 'muzhchinam/odezhda/kostyumy',
    'одежда пиджаки и жакеты': 'muzhchinam/odezhda/pidzhaki-i-zhakety',
    'одежда рубашки': 'muzhchinam/odezhda/rubashki',
    'одежда толстовки': 'muzhchinam/odezhda/tolstovki',
    'одежда футболки': 'muzhchinam/odezhda/futbolki-i-mayki',
    'дом ванные аксесуары': 'dom-i-dacha/vannaya/aksessuary',
    'дом ванная сантехника': 'dom/vannaya/santehnika',
    'дом аксесуары для напитков': 'dom-i-dacha/kuhnya/aksessuary-dlya-napitkov',
    'дом аксесуары для специй': 'dom-i-dacha/kuhnya/aksessuary-dlya-spetsiy',
    'дом бокалы и стаканы': 'dom-i-dacha/kuhnya/bokaly-i-stakany',
    'дом декоративная посуда': 'dom/kuhnya/dekorativnaya-posuda',
    'дом кухонный декор': 'dom-i-dacha/kuhnya/kuhonniy-dekor',
    'дом ножи': 'dom-i-dacha/kuhnya/nozhi-kuhonnye',
    'дом порядок': 'dom-i-dacha/kuhnya/poryadok-na-kuhne',
    'дом термосы': 'dom-i-dacha/kuhnya/termosy-termosumki',
    'дом часы': 'dlya-doma/predmety-interera/chasy',
    'дом декор настенный': 'dom/spalnya/dekoratsii-nastennye',
    'дом спальня мебель': 'dom/spalnya/mebel',
    'дом хранение вещей': 'dom/spalnya/hranenie-veshchey',
    'отдых на природе': 'dom-i-dacha/otdyh-na-prirode',
    'дом порфюмерия': 'dlya-doma/predmety-interera/parfyumeriya',
    'аксесуары кошельки': 'aksessuary/koshelki-i-kreditnitsy',
    'электроника гарнитуры': 'elektronika/igry-i-razvlecheniya/aksessuary/garnitury',
    'электроника консоли': 'elektronika/razvlecheniya-i-gadzhety/igrovye-konsoli/igrovye-konsoli',
    'электроника ноут переферия': 'elektronika/noutbuki-periferiya',
    'электроника смартфоны': 'elektronika/smartfony-i-telefony/vse-smartfony',
    'электроника смарт часы': 'elektronika/smart-chasy',
    'электроника умный дом': 'elektronika/umnyy-dom',
    'ЧАЙ': 'pitanie/chay-kofe/chay',
    'рыбалка приманки и прикормки': 'sport/ohota-i-rybalka/rybalka/primanki-i-prikormki',
    'рыбалка': 'sport/ohota-i-rybolovstvo/rybalka',
    'охота и рыбалка': 'sport/vidy-sporta/ohota-i-rybolovstvo',
    'туристическая мебель': 'sport/vidy-sporta/turizm-kemping/snaryazhenie/turisticheskaya-mebel',
    'кемпинг аксесуары': 'sport/vidy-sporta/turizm-kemping/aksessuary',
    'часы': 'yuvelirnye-ukrasheniya/chasy',
    'наборы инструментов': 'tovary-dlya-remonta/instrumenty/nabory-instrumentov',
    'электроинструменты': 'dlya-remonta/instrumenty-i-osnastka/sverlenie-dolblenie-zakruchivanie',
    'кемпинг и отдых': 'dom/dachniy-sezon/tovary-dlya-kempinga-piknika-i-otdyha',
    'уход за авто': 'aksessuary/avtotovary/uhod-za-avtomobilem',
    'автоэлектроника': 'elektronika/avtoelektronika',
    'уход за авто 2': 'avtotovary/avtoaksessuary-i-dopolnitelnoe-oborudovanie/aksessuary-v-salon-i-bagazhnik/ukxod-za-avtomobilem',
    'авто инструменты': 'avtotovary/instrumenty',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
    # '': '',
}